Add a second git hook for cscope

diff --git a/.git_template/hooks/pre-merge b/.git_template/hooks/pre-merge
--- a/.git_template/hooks/pre-merge
+++ b/.git_template/hooks/pre-merge
@@ -1,2 +1,15 @@
-#!/bin/sh
-.git/hooks/ctags >/dev/null 2>&1 &
+#!/bin/bash
+
+here="$(dirname "${0}")"
+cd "${here}/pre-commit.d" || exit
+
+for hook in *; do
+  bash ${hook}
+  RESULT=$?
+  if [ ${RESULT} != 0 ]; then
+    echo "pre-commit.d/${hook} returned non-zero: ${RESULT}, abort commit"
+    exit $RESULT
+  fi
+done
+
+exit 0
